#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_45
export M2=$OPENSHIFT_DATA_DIR/apache-maven-3.3.3/bin
export MAVEN_OPTS="-Xms384m -Xmx412m"
export PATH=$JAVA_HOME/bin:$M2:$PATH

export SERVER_PORT=${OPENSHIFT_DIY_PORT}
export SERVER_ADDRESS=${OPENSHIFT_DIY_IP}

cd $OPENSHIFT_REPO_DIR
nohup java -jar target/*.jar &